### ISSUE TITLE
pip install Flask-WXPay failed.

### ISSUE THREAD

**Issue by dsphoebe** [codeif/Flask-WXPay#2]
```
Downloading/unpacking Flask-WXPay==0.1.13 (from -r requirements.txt (line 19))
  Downloading Flask-WXPay-0.1.13.tar.gz
  Running setup.py (path:/home/ubuntu/.virtualenvs/syh/build/Flask-WXPay/setup.py) egg_info for package Flask-WXPay
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/ubuntu/.virtualenvs/syh/build/Flask-WXPay/setup.py", line 7, in <module>
        readme = f.read()
      File "/home/ubuntu/.virtualenvs/syh/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/ubuntu/.virtualenvs/syh/build/Flask-WXPay/setup.py", line 7, in <module>

    readme = f.read()

  File "/home/ubuntu/.virtualenvs/syh/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/ubuntu/.virtualenvs/syh/build/Flask-WXPay
Storing debug log for failure in /tmp/user/1000/tmp3kt9ks4d
```

**Comment by codeif** [comment]
在3.4环境下测试安装成功

`
root@f57d9f3bba0b:/# python --version
Python 3.4.8
root@f57d9f3bba0b:/# pip install Flask-WXPay
Collecting Flask-WXPay
  Downloading https://files.pythonhosted.org/packages/37/90/02cbbc05e60ef54ed8ed30469afb8f7020ab850ad05fc638d6bda9e857cf/Flask-WXPay-0.1.13.tar.gz
Collecting requests (from Flask-WXPay)
  Downloading https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 173kB/s
Collecting idna<2.7,>=2.5 (from requests->Flask-WXPay)
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 560kB/s
Collecting certifi>=2017.4.17 (from requests->Flask-WXPay)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 561kB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests->Flask-WXPay)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 576kB/s
Collecting urllib3<1.23,>=1.21.1 (from requests->Flask-WXPay)
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 332kB/s
Building wheels for collected packages: Flask-WXPay
  Running setup.py bdist_wheel for Flask-WXPay ... done
  Stored in directory: /root/.cache/pip/wheels/43/30/50/2c0cd183e03d02b19eeb070ec8b00e6aa2592e5b995864c535
Successfully built Flask-WXPay
Installing collected packages: idna, certifi, chardet, urllib3, requests, Flask-WXPay
Successfully installed Flask-WXPay-0.1.13 certifi-2018.4.16 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22
`
