### ISSUE TITLE
微信支付证书验证失败

### ISSUE THREAD

**Issue by naihuhu** [codeif/Flask-WXPay#8]
在调用wxpay.transfers()方法[微信支付企业付款：https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers]接口时，项目启动一段时间后会返回“证书出错，请登录微信支付商户平台下载证书”错误，重启项目后错误消失，但是过一段时间之后，错误又会复现出来，初步怀疑是requests.Session的ssl握手机制问题。

**Comment by codeif** [comment]
从微信平台下载证书后，配置下面两项看看

WXPAY_APICLIENT_CERT_PATH 和 WXPAY_APICLIENT_KEY_PATH

**Comment by naihuhu** [comment]
都配置了，项目启动之后，接口调用正常，说明配置和证书都没有问题，但是大概一周之后接口会返回证书出错的错误。重启项目，错误消失，过段时间又会复现，期间没有修改任何项目配置和证书文件。

**Comment by codeif** [comment]
把错误的信息贴出来看看，或者直接google对应的错误提示，看看有没有类似问题的解决方案。
